### ISSUE TITLE
Everest-pipeline 2.0.11 on Windows 10

### ISSUE THREAD

**Issue by ajamyajax** [rodluger/everest#17]
Installed everest-pipeline 2.0.11 on Windows 10 with the latest python, but cannot get past "import everest" in an app with these errors:

...\Python\Python37-32\lib\site-packages\everest\__init__.py", line 22, in <module>
    from . import mathutils
...\Python\Python37-32\lib\site-packages\everest\mathutils.py", line 16, in <module>
    from scipy.misc import comb
ImportError: cannot import name 'comb' from 'scipy.misc' (...\Python\Python37-32\lib\site-packages\scipy\misc\__init__.py)

this fix: from scipy.special import comb
...

When past the above (after fix mentioned) I get this:

  File "...Python\Python37-32\lib\site-packages\everest\__init__.py", line 23, in <module>
    from . import transit
  File "...Python\Python37-32\lib\site-packages\everest\transit.py", line 19, in <module>
    import pysyzygy as ps
  File "...Python\Python37-32\lib\site-packages\pysyzygy\__init__.py", line 16, in <module>
    subprocess.call(["make"], cwd = cwd)
  File "...Python\Python37-32\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "...Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "...Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Any ideas? And pysyzygy installed just fine.

**Comment by rodluger** [comment]
Hi @ajamyajax, sorry for the delay. I just pushed `v2.0.12` to `PyPI`, and this includes a [hack](https://github.com/rodluger/everest/commit/6bcf981e19f4dab158e35fc984430d3bc31de90f) to fail silently if the `pysyzygy` import fails. Can you try again and let me know if it works?

PS: pysyzygy (which I wrote) is a terrible piece of software -- it actually delays the installation of the C code until it's *imported* for the first time, so even though it "installs" fine, it can still fail when you use it. Sorry you have to deal with this! I've been meaning to phase it out, but haven't had the time yet.

**Comment by ajamyajax** [comment]
Yes your fix works!  Everest-pipeline 2.0.12 installs just fine now and import etc works also.
Thanks.
