### ISSUE TITLE
aux reserve word request

### ISSUE THREAD

**Issue by ajamyajax** [rodluger/everest#8]
Dear Rodrigo,

A minor issue in the /everest/missions/k2/ source, but I believe "aux" is a reserve word in Windows back to the MS DOS days where a file cannot be so named.  Would it be possible to rename this to something else, so Windows users don't have to manually fix this in the setup code for each new EVEREST update?

Thanks, Mark

**Comment by rodluger** [comment]
Thanks for pointing this out! I'm surprised EVEREST works at all on Windows, since I've never tested it on a non-Linux system :) I'm planning on re-writing the code again in the next few months, so I'll fix this in the next big update.

**Comment by rodluger** [comment]
Finally got around to this. Changed it to "utils.py".

**Comment by ajamyajax** [comment]
Thanks, I will test this on Windows also when I get a chance.

**Comment by ajamyajax** [comment]
Ok when I installed Everest-Master 2.0.9 with python setup.py install on my
Windows configuration, it worked just fine.  Thanks. I should add that I
custom pre-installed the previous george 0.2.1 package with a few fixes or
workarounds that other users might get run-time errors with if don't do the
same. I haven't fixed george 0.3.0 yet, but from quick test install there
other fixes will be needed for Windows too.

I do get a new run-time error with a c2 candidate as shown that worked
before in version 2.0.8.  I can see that a season attribute must be added
now and will check the documentation, but here is the actual error anyway.
And thanks again for all your efforts. Your package is more well-written
than many I have tested and I thank you for that also.

My test platform:
Microsoft Windows [Version 10]
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit
(Intel)] on win32

ERROR [everest.utils.ExceptionHook()]: AttributeError: Please choose a
`season` for this target: [2, 111, 112].
ERROR [everest.utils.ExceptionHook()]:   File "everest_test.py", line 12,
in <module>    star = everest.Everest(203925865)  # c2 candidate
ERROR [everest.utils.ExceptionHook()]:   File
"C:\python36\lib\site-packages\everest_pipeline-2.0.9-py3.6.egg\everest\user.py",
line 325, in __init__    cadence=cadence)
ERROR [everest.utils.ExceptionHook()]:   File
"C:\python36\lib\site-packages\everest_pipeline-2.0.9-py3.6.egg\everest\user.py",
line 157, in DownloadFile    "Please choose a `season` for this target:
%s." % season)
Traceback (most recent call last):
  File "everest_test.py", line 12, in <module>
    star = everest.Everest(203925865)  # c2 candidate
  File
"C:\python36\lib\site-packages\everest_pipeline-2.0.9-py3.6.egg\everest\user.py",
line 325, in __init__
    cadence=cadence)
  File
"C:\python36\lib\site-packages\everest_pipeline-2.0.9-py3.6.egg\everest\user.py",
line 157, in DownloadFile
    "Please choose a `season` for this target: %s." % season)
AttributeError: Please choose a `season` for this target: [2, 111, 112].

**Comment by ajamyajax** [comment]
Follow-up: I added the season as a parameter as shown, and now get this
memory error on my older 3GB RAM PC..  I know, more RAM would probably fix
this problem but any large allocation variable clean up you can think of
would also help.  Thanks again.

 star = everest.Everest(203925865, season=2)  # c2 candidate

INFO  [everest.user.DownloadFile()]: Found cached file.
INFO  [everest.user.load_fits()]: Loading FITS file for 203925865.
INFO  [everest.basecamp.compute()]: Computing the model...
ERROR [everest.utils.ExceptionHook()]: MemoryError
ERROR [everest.utils.ExceptionHook()]:   File "everest_test.py", line 108,
in <module>    star.compute()
ERROR [everest.utils.ExceptionHook()]:   File
"C:\python36\lib\site-packages\everest_pipeline-2.0.9-py3.6.egg\everest\user.py",
line 384, in compute    super(Everest, self).compute()
ERROR [everest.utils.ExceptionHook()]:   File
"C:\python36\lib\site-packages\everest_pipeline-2.0.9-py3.6.egg\everest\basecamp.py",
line 413, in compute    XM = self.X(n, m)
ERROR [everest.utils.ExceptionHook()]:   File
"C:\python36\lib\site-packages\everest_pipeline-2.0.9-py3.6.egg\everest\basecamp.py",
line 323, in X    X = np.product(list(multichoose(X1.T, i + 1)), axis=1).T
ERROR [everest.utils.ExceptionHook()]:   File
"C:\python36\lib\site-packages\numpy\core\fromnumeric.py", line 1849, in
product    return um.multiply.reduce(a, axis=axis, dtype=dtype, out=out,
**kwargs)
Traceback (most recent call last):
  File "everest_test.py", line 108, in <module>
    star.compute()
  File
"C:\python36\lib\site-packages\everest_pipeline-2.0.9-py3.6.egg\everest\user.py",
line 384, in compute
    super(Everest, self).compute()
  File
"C:\python36\lib\site-packages\everest_pipeline-2.0.9-py3.6.egg\everest\basecamp.py",
line 413, in compute
    XM = self.X(n, m)
  File
"C:\python36\lib\site-packages\everest_pipeline-2.0.9-py3.6.egg\everest\basecamp.py",
line 323, in X
    X = np.product(list(multichoose(X1.T, i + 1)), axis=1).T
  File "C:\python36\lib\site-packages\numpy\core\fromnumeric.py", line
1849, in product
    return um.multiply.reduce(a, axis=axis, dtype=dtype, out=out, **kwargs)
MemoryError

**Comment by dfm** [comment]
george >=0.3 has been extensively tested on windows so please open an issue on the george GitHub page if you have a bug.

**Comment by ajamyajax** [comment]
Thanks, I will do that when I can.

**Comment by ajamyajax** [comment]
Re: george 0.3.0 on my Windows 10 PC: I installed the current Microsoft
Visual Studio (2017 community edition), an upgrade here.  Then ran pip
install george, and all my tests worked just fine.  So that was my 0.3
issue and apparently is resolved now. Thanks again.
