### ISSUE TITLE
Everest with george 0.3?

### ISSUE THREAD

**Issue by hposborn** [rodluger/everest#9]
It's now pretty much impossible to install george 0.21 (there may be a way to git checkout an older version, but it's a hassle!). Any chance of updating everest to run with 0.3? There's not too much difference, except that WhiteKernel is now part of the george.GP object rather than existing as a stand-alone kernel. Hence the import error:

`ImportError: cannot import name 'WhiteKernel'
`

**Comment by dfm** [comment]
Does `pip install george==0.2.1` not work?

**Comment by hposborn** [comment]
Indeed it does! I was stumbling around with HODLR and Eigen libraries in the setup.py route... 

But I really would like everest & george 0.3 running together (the WhiteKernel in 0.2.1 is causing me the trouble that led to my "seperating kernel contributions" issue with george).

**Comment by dfm** [comment]
Totally. We're actually planning on switching to celerite because it seems to be working pretty well. We'll keep you posted!

**Comment by rodluger** [comment]
@hposborn I'm working on this right now. The next update to everest will work with both versions of george. I'll probably release it sometime in the next two weeks, along with light curves through campaign 13. 
@dfm is there an easy way to compute the gradient of the likelihood with respect to the white noise term in george 0.3? It's not an element in the parameter vector, so the built-in function doesn't return it. I'm currently evaluating it as

![image](https://user-images.githubusercontent.com/9323819/33046294-3a61e972-ce05-11e7-8078-2b310ff48228.png)

Does this seem about right?

**Comment by dfm** [comment]
Can you use the `white_noise`/`fit_white_noise` parameters in the GP object ([docs](http://george.readthedocs.io/en/latest/user/gp/#george.GP))? Then it will have its gradient computed...

**Comment by rodluger** [comment]
Ah, didn't see that option. Perfect -- thanks!

**Comment by rodluger** [comment]
Finally got around to this, sorry for the wait!

**Comment by zexyswami** [comment]
having the same problem ie `ImportError: cannot import name 'WhiteKernel'`. I tried using `pip install george==0.2.1`, but received error :
`Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-z6_tH1/george/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-YU25gB-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-z6_tH1/george/`
